//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by faac_wingui.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FAAC_WINGUI_DIALOG          102
#define IDS_UndefinedShort              102
#define IDS_UndefinedLong               103
#define IDS_InvalidJob                  104
#define IDS_EncoderJobShort             105
#define IDS_EncoderJobLong              106
#define IDS_MidSide                     107
#define IDS_UseLfe                      109
#define IDS_NoListItemSelected          110
#define IDS_JobTypeColumn               111
#define IDS_JobInfoColumn               112
#define IDS_EncoderGeneralShort         113
#define IDS_EncoderId3Short             114
#define IDS_TabUndefined                115
#define IDS_EncoderQualityShort         116
#define IDS_SelectSourceDirDlgCaption   117
#define IDS_SelectTargetDirDlgCaption   118
#define IDS_ErrorDuringDirectorySelection 119
#define IDS_AllFilesFilter              120
#define IDS_WavFilesFilter              121
#define IDS_EndSourceFileStandardExtension 122
#define IDS_ErrorDuringFileSelection    123
#define IDS_AacFilesFilter              124
#define IDS_EndTargetFileStandardExtension 125
#define IDS_UseTns                      126
#define IDS_UseLtp                      127
#define IDR_MAINFRAME                   128
#define IDS_AacProfileLc                128
#define IDD_PROPERTIESTABPARENTDIALOG   129
#define IDS_AacProfileMain              129
#define IDD_ENCODERGENERALPAGEDIALOG    130
#define IDS_AacProfileSsr               130
#define IDD_FLOATINGPROPERTYDIALOG      131
#define IDS_DetailedEncoderJobDescriptionString 131
#define IDD_PROPERTIESDUMMYPARENTDIALOG 132
#define IDS_JobListFileFilter           132
#define IDD_ENCODERID3PAGEDIALOG        133
#define IDS_JobListStandardExtension    133
#define IDD_ENCODERQUALITYPAGEDIALOG    134
#define IDS_ErrorWhileSavingJobList     134
#define IDS_SearchParametersInvalid     135
#define IDD_PROCESSJOBSTATUSDIALOG      136
#define IDS_ErrorProcessingJobSelection 136
#define IDR_TOOLBARMAIN                 137
#define IDS_FilterDidntFindFiles        137
#define IDS_ErrorCreatingNestedEncoderJob 138
#define IDS_ErrorWhileLoadingJobList    139
#define IDD_ASKCREATEDIRECTORYDIALOG    139
#define IDS_JobNofM                     140
#define IDS_SubJobNofM                  141
#define IDS_ErrorCreatingDirectory      142
#define IDS_FilterJobSupplementaryInfo  143
#define IDS_UserRefusedToCreateTargetDirectory 144
#define IDS_FaacEncSetConfigurationFailed 145
#define IDS_CouldntOpenInputFile        146
#define IDS_FaacEncEncodeFrameFailed    147
#define IDS_JobProcessInfoColumn        148
#define IDS_OutcomeUnprocessed          149
#define IDS_OutcomeSuccessfullyProcessed 150
#define IDS_OutcomePartiallyProcessed   151
#define IDS_OutcomeUserAbort            152
#define IDS_OutcomeError                153
#define IDS_FollowUp                    154
#define IDS_ErrorCreatingTargetDiretory 155
#define IDS_InvalidTargetDirectory      156
#define IDS_HadUnsuccessfulJobs         157
#define IDS_AacProfileLtp               158
#define IDS_MpegVersion2                159
#define IDS_MpegVersion4                160
#define IDC_LISTJOBS                    1000
#define IDC_BUTTONADDENCODERJOB         1001
#define IDC_TAB1                        1002
#define IDC_LABELNOSELECTION            1004
#define IDC_EDITSOURCEDIR               1006
#define IDC_BUTTONBROWSESOURCEDIR       1007
#define IDC_EDITTARGETDIR               1008
#define IDC_BUTTONBROWSETARGETDIR       1009
#define IDC_EDITSOURCEFILE              1010
#define IDC_BUTTONBROWSESOURCEFILE      1011
#define IDC_EDITTARGETFILE              1012
#define IDC_BUTTONBROWSETARGETFILE      1013
#define IDC_EDITBITRATE                 1014
#define IDC_EDITBANDWIDTH               1015
#define IDC_CHECKMIDSIDE                1016
#define IDC_CHECKUSELFE                 1017
#define IDC_LABELDEBUGTAG               1018
#define IDC_EDITARTIST                  1019
#define IDC_EDITTRACK                   1020
#define IDC_EDITTITLE                   1021
#define IDC_EDITURL                     1023
#define IDC_EDITALBUM                   1024
#define IDC_EDITYEAR                    1025
#define IDC_EDITCOMPOSER                1026
#define IDC_EDITORIGINALARTIST          1027
#define IDC_CHECKCOPYRIGHT              1029
#define IDC_EDITCOMMENT                 1030
#define IDC_EDITENCODEDBY               1031
#define IDC_COMBOGENRE                  1032
#define IDC_BUTTONDELETEJOBS            1033
#define IDC_BUTTONPROCESSSELECTED       1034
#define IDC_LABELTOPSTATUSTEXT          1035
#define IDC_PROGRESS1                   1036
#define IDC_LABELBOTTOMSTATUSTEXT       1037
#define IDC_BUTTONABORT                 1038
#define IDC_BUTTONPAUSE                 1039
#define IDC_BUTTONCONTINUE              1041
#define IDC_CHECKREMOVEPROCESSEDJOBS    1042
#define IDC_CHECKUSETNS                 1043
#define IDC_CHECKUSELTP                 1044
#define IDC_RADIOAACPROFILELC           1045
#define IDC_RADIOAACPROFILEMAIN         1046
#define IDC_RADIOAACPROFILESSR          1047
#define IDC_BUTTON1                     1048
#define IDC_BUTTONSAVEJOBLIST           1049
#define IDC_RADIOAACPROFILELTP          1049
#define IDC_BUTTONLOADJOBLIST           1050
#define IDC_BUTTONDUPLICATESELECTED     1051
#define IDC_CHECKRECURSIVE              1052
#define IDC_BUTTONPROCESSALL            1053
#define IDC_BUTTONOPENPROPERTIES        1054
#define IDC_BUTTONMINIMIZEAPP           1055
#define IDC_BUTTONEXPANDFILTERJOB       1056
#define IDC_LABELTARGETDIR              1057
#define IDC_BUTTONNO                    1058
#define IDC_BUTTONALWAYS                1059
#define IDC_BUTTONYES                   1060
#define IDC_BUTTONNEVER                 1061
#define IDC_BUTTONADDFILTERENCODERJOB   1062
#define IDC_BUTTONADDEMPTYENCODERJOB    1063
#define IDC_RADIOMPEGVERSION2           1064
#define IDC_RADIOMPEGVERSION4           1065
#define ID_BUTTON32771                  32771
#define ID_BUTTON32772                  32772
#define ID_BUTTON32773                  32773
#define ID_BUTTON32774                  32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
